Abdul Qadeer Roll No: PIAIC143312

In [1]:
import numpy as np

In [2]:
my_arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [3]:
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [6]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.arange(0,13,4)

array([ 0,  4,  8, 12])

In [8]:
np.linspace(2,8, 4)

array([2., 4., 6., 8.])

In [9]:
un_sorted_arr = np.array([90,8,5,4,7,1])

In [10]:
np.sort(un_sorted_arr)

array([ 1,  4,  5,  7,  8, 90])

In [11]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8,9])

In [12]:
np.concatenate((arr_1, arr_2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_3d = np.array([[[1,2,3,],
                    [4,5,6,],
                   [7,8,9],
                   [10,11,12]],
                   [[1,2,3,],
                    [4,5,6,],
                   [7,8,9],
                    [10,11,12]
                   ]]
                  
                   )

In [14]:
arr_3d.shape

(2, 4, 3)

In [15]:
arr_3d.ndim

3

In [16]:
arr_3d.size

24

In [17]:
arr_3d.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [18]:
a = np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a2 = a[np.newaxis, :]

In [21]:
a2.shape

(1, 10)

In [22]:
a3 = a2[np.newaxis, :]

In [23]:
a3.shape, a3.size, a3.ndim

((1, 1, 10), 10, 3)

In [24]:
an_a = np.array([1,2,3,4,5,6])
an_a.shape

(6,)

In [25]:
an_b = np.expand_dims(an_a, 1)
an_b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
an_b.shape


(6, 1)

In [27]:
an_c = np.expand_dims(an_b, axis = 0)
an_c

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [28]:
an_c.shape

(1, 6, 1)

In [29]:
an_a

array([1, 2, 3, 4, 5, 6])

In [30]:
an_a[3]

4

In [31]:
an_a[-5:4]

array([2, 3, 4])

np.nonzero()         ----------->             couldn't understand this function

In [32]:
a_1 = np.array([[1, 1],
            [2,2]])
a_2 = np.array([[3,3],
            [4,4]])

In [33]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [34]:
np.hstack((a_2, a_1))

array([[3, 3, 1, 1],
       [4, 4, 2, 2]])

In [35]:
split_arr = np.arange(21).reshape(3, 7)
split_arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [36]:
np.hsplit(split_arr,(2, 3))

[array([[ 0,  1],
        [ 7,  8],
        [14, 15]]),
 array([[ 2],
        [ 9],
        [16]]),
 array([[ 3,  4,  5,  6],
        [10, 11, 12, 13],
        [17, 18, 19, 20]])]

In [37]:
org = np.array([1,2,3,4,5])
org 

array([1, 2, 3, 4, 5])

In [38]:
deep_copy = org.copy()

In [39]:
deep_copy[3] = 99

In [40]:
org, deep_copy

(array([1, 2, 3, 4, 5]), array([ 1,  2,  3, 99,  5]))

In [41]:
org + deep_copy

array([  2,   4,   6, 103,  10])

In [42]:
deep_copy.sum()

110

In [43]:
deep_copy.max()

99

In [44]:
deep_copy.min()

1

In [45]:
rng = np.random.default_rng().random(3)           # couldn't understand default_rng
rng

array([0.83646956, 0.58647665, 0.45064656])

In [46]:
ar_ = np.array([1,2,1,1,4,2,6,7,6,6])
unique_num = np.unique(ar_)
unique_num

array([1, 2, 4, 6, 7])

In [47]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [49]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.flip(arr)

array([[5, 4, 3],
       [2, 1, 0]])

In [51]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a1 = x.flatten()
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
a1[0] = 89
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a1

array([89,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
a2 = x.ravel()
a2[0] = 675

In [61]:
x

array([[675,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [62]:
a2

array([675,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [63]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [77]:
max?, max??

In [78]:
np.save("my_file", a2)

In [80]:
b = np.load("my_file.npy")
b

array([675,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [83]:
np.savetxt("my_file.txt", a2)

In [84]:
np.loadtxt("my_file.txt")

array([675.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])