Abdul Qadeer Roll No: PIAIC143312

In [1]:
import numpy as np

In [2]:
my_arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [10]:
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [5]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.arange(0,13,4)

array([ 0,  4,  8, 12])

In [9]:
np.linspace(2,8, 4)

array([2., 4., 6., 8.])

In [11]:
un_sorted_arr = np.array([90,8,5,4,7,1])

In [12]:
np.sort(un_sorted_arr)

array([ 1,  4,  5,  7,  8, 90])

In [18]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8,9])

In [20]:
np.concatenate((arr_1, arr_2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr_3d = np.array([[[1,2,3,],
                    [4,5,6,],
                   [7,8,9],
                   [10,11,12]],
                   [[1,2,3,],
                    [4,5,6,],
                   [7,8,9],
                    [10,11,12]
                   ]]
                  
                   )

In [39]:
arr_3d.shape

(2, 4, 3)

In [40]:
arr_3d.ndim

3

In [41]:
arr_3d.size

24

In [46]:
arr_3d.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [51]:
a = np.arange(10)

In [52]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a2 = a[np.newaxis, :]

In [64]:
a2.shape

(1, 10)

In [65]:
a3 = a2[np.newaxis, :]

In [71]:
a3.shape, a3.size, a3.ndim

((1, 1, 10), 10, 3)

3